from . import res_partner
from . import res_users
from . import peart_nomenclator_mixin
from . import peart_care_type
from . import peart_urgency_level
from . import peart_admission
from . import peart_testimonial
from . import peart_tour_booking
from . import peart_waitlist
from . import peart_site_settings
from . import peart_gallery_photo
from . import hr_applicant
from . import product_template
