from . import peart_resident
from . import peart_resident_family_link
from . import peart_resident_consent
from . import peart_scale
from . import peart_resident_assessment
from . import peart_resident_clinical
from . import peart_daily_log
from . import peart_medication_administration
from . import peart_incident
from . import peart_family_portal
from . import res_config_settings
from . import ir_actions_report
from . import ai_clinical_assistant
from . import peart_clinical_assistant_wizard
from . import peart_shift_handover
from . import peart_family_note_draft_wizard
from . import ai_clinical_actions
from . import peart_clinical_action_request
from . import peart_nursing_task_wizard
from . import peart_admission
